//Markers
export const UPDATE_MARKERS = 'UPDATE_MARKERS'
export const UPDATE_MARKER = 'UPDATE_MARKER'
export const DELETE_MARKER = 'DELETE_MARKER'
export const EDIT_MARKER = 'EDIT_MARKER'

export const ACTIVE_INDEX = 'ACTIVE_INDEX'
export const ACTIVE_CATEGORY = 'ACTIVE_CATEGORY'
export const ACTIVE_CONVERSATION = 'ACTIVE_CONVERSATION'
export const  SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const  SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'
export const  MESSAGE_WINDOW_OPEN = 'MESSAGE_WINDOW_OPEN'
export const  MESSAGE_WINDOW_CLOSE = 'MESSAGE_WINDOW_CLOSE'
export const  SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE'
export const  MESSAGE_WINDOW_TOGGLE = 'MESSAGE_WINDOW_TOGGLE'

export const SETPOSITION = 'SETPOSITION'
export const GET_LOCATION = 'GET_LOCATION'

//User
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGNUP = 'SIGNUP'
export const USER_MARKERS = 'USER_MARKERS'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

//Map
export const UPDATE_BOUNDS = 'UPDATE_BOUNDS'
export const UPDATE_CENTER = 'UPDATE_CENTER'

//API
export const GET_MARKERS = 'GET_MARKERS'
export const ADD_MARKER = 'ADD_MARKER'
export const GET_CONVERSATIONS = 'GET_CONVERSATIONS'
export const ADD_CONVERSATION = 'ADD_CONVERSATION'
export const GET_MESSAGES = 'GET_MESSAGES'
export const GET_MESSAGE = 'GET_MESSAGE'

//Modal
export const MODAL_OPEN = 'MODAL_OPEN'
export const MODAL_CLOSE = 'MODAL_CLOSE'
export const SET_MODAL_DATA = 'SET_MODAL_DATA'

//LOCALSTOAGE
export const SAVE_USER_TO_LOCALSTORAGE = 'SAVE_USER_TO_LOCALSTORAGE'
export const LOAD_USER_FROM_LOCALSTORAGE = 'LOAD_USER_FROM_LOCALSTORAGE'

//STATS
export const UPDATE_STATS = 'UPDATE_STATS'
